# mongodb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-ci-db-deployment
  labels:
    app: flow-ci-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-ci-db
  template:
    metadata:
      labels:
        app: flow-ci-db
    spec:
      volumes:
        - name: data
          hostPath:
            path: /flowci/db
            type: DirectoryOrCreate
      containers:
        - name: db
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: data
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"