# mongodb
apiVersion: v1
kind: Service
metadata:
  name: flowci-db-service
spec:
  selector:
    app: flowci-db
  ports:
    - protocol: TCP
      port: 27017

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-db-deployment
  labels:
    app: flowci-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowci-db
  template:
    metadata:
      labels:
        app: flowci-db
    spec:
      volumes:
        - name: data
          hostPath:
            path: /flowci/db
            type: DirectoryOrCreate
      containers:
        - name: db
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: data
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"