# minio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-ci-minio-deployment
  labels:
    app: flow-ci-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-ci-minio
  template:
    metadata:
      labels:
        app: flow-ci-minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          env:
            - name: MINIO_ACCESS_KEY
              value: "12345"
            - name: MINIO_SECRET_KEY
              value: "12345"
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "200m"