# web
apiVersion: v1
kind: Service
metadata:
  name: flowci-web-service
spec:
  selector:
    app: flowci-web
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowci-web-deployment
  labels:
    app: flowci-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flowci-web
  template:
    metadata:
      labels:
        app: flowci-web
    spec:
      containers:
        - name: web
          image: flowci/web:dev
          env:
            - name: FLOWCI_SERVER_URL
              value: TODO
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"