# zk
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-ci-zk-deployment
  labels:
    app: flow-ci-zk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow-ci-zk
  template:
    metadata:
      labels:
        app: flow-ci-zk
    spec:
      containers:
        - name: zk
          image: zookeeper:3.6
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "200m"